# Pipeline combinada para CI e CD
name: CI/CD Pipeline

on:
  push:
    branches: ["main"]

jobs:
  # Job de CI: Build e Push das imagens Docker
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Criando .env para as credenciais
        run: |
          echo "DB_HOST=${{ secrets.DB_HOST }}" > back-end/.env
          echo "DB_USER=${{ secrets.DB_USER }}" >> back-end/.env
          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> back-end/.env
          echo "DB_NAME=${{ secrets.DB_NAME }}" >> back-end/.env

      - name: Login DockerHub
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

      - name: Build Backend Docker image
        run: docker build -t maathjason/pipelinegarms-backend -f back-end/Dockerfile back-end

      - name: Build Frontend Docker image
        run: docker build -t maathjason/pipelinegarms-frontend -f front-end/Dockerfile front-end

      - name: Push Backend Docker image to DockerHub
        run: docker push maathjason/pipelinegarms-backend

      - name: Push Frontend Docker image to DockerHub
        run: docker push maathjason/pipelinegarms-frontend